version: "3.0"

services:
  mongodb:
    image: mongo
    container_name: mongo_db_container
    ports:
      # local --> contenedor
      - 27018:27017
    restart: always
    volumes:
      - ./data:/data/configdb
      - ./data:/data/mongo_db_container

  api:
    build: .
    container_name: api_container
    ports:
      - 8001:8000
    depends_on:
      - mongodb
    restart: always
    volumes:
      - .:/usr/src/app

volumes:
  mongo_afer_4:
